# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: OTKRSK
email: buzzmeh@otakrosak.com
description: > # this means to ignore newlines until "baseurl:"
  The cat was kind of sick of his routine. Up until today, everyday was
  the same. "How could I change it?", he asked himself.

  He was deeply disturbed.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://otakrosak.com" # the base hostname & protocol for your site
twitter_username: otkrsk
github_username:  otkrsk

# Build settings
markdown: kramdown
